services:
  redis-master:
    image: redis:latest
    volumes:
      - ./master/redis.conf:/etc/redis/redis.conf:ro
      - redis_master_data:/data/redis/master
    command: redis-server /etc/redis/redis.conf
    ports:
      - "127.0.0.1:6231:6231"

  redis-replica-one:
    image: redis:latest
    volumes:
      - ./replica-one/redis.conf:/etc/redis/redis.conf:ro
      - redis_replica_one_data:/data/redis/replica-one
    command: redis-server /etc/redis/redis.conf
    ports:
      - "127.0.0.1:6232:6232"
    depends_on:
      - redis-master

  redis-replica-two:
    image: redis:latest
    volumes:
      - ./replica-two/redis.conf:/etc/redis/redis.conf:ro
      - redis_replica_two_data:/data/redis/replica-two
    command: redis-server /etc/redis/redis.conf
    ports:
      - "127.0.0.1:6233:6233"
    depends_on:
      - redis-master

  redis-sentinel-one:
    image: redis:latest
    volumes:
      - ./sentinel-one/redis.conf:/etc/redis/redis.conf
      - redis_sentinel_one_data:/data/redis/sentinel-one
    command: redis-sentinel /etc/redis/redis.conf
    ports:
      - "127.0.0.1:7231:7231"
    depends_on:
      - redis-master

  redis-sentinel-two:
    image: redis:latest
    volumes:
      - ./sentinel-two/redis.conf:/etc/redis/redis.conf
      - redis_sentinel_two_data:/data/redis/sentinel-two
    command: redis-sentinel /etc/redis/redis.conf
    ports:
      - "127.0.0.1:7232:7232"
    depends_on:
      - redis-master

  redis-sentinel-three:
    image: redis:latest
    volumes:
      - ./sentinel-three/redis.conf:/etc/redis/redis.conf
      - redis_sentinel_three_data:/data/redis/sentinel-three
    command: redis-sentinel /etc/redis/redis.conf
    ports:
      - "127.0.0.1:7233:7233"
    depends_on:
      - redis-master

volumes:
  redis_master_data:
  redis_replica_one_data:
  redis_replica_two_data:
  redis_sentinel_one_data:
  redis_sentinel_two_data:
  redis_sentinel_three_data:
